class HotelEntity {
  final String city;
  final String image;
  final String hotelName;
  final double rating;
  final double lat;
  final double long;
  final int price;

  HotelEntity({
    required this.city,
    required this.image,
    required this.hotelName,
    required this.rating,
    required this.lat,
    required this.long,
    required this.price,
  });
}

List<HotelEntity> hotelList = [
  HotelEntity(
    city: 'Yogyakarta',
    image: 'assets/hotels/phoenix_hotel.jpg',
    hotelName: 'The Phoenix Hotel Yogyakarta',
    rating: 4.8,
    price: 1450000,
    lat: -7.7833,
    long: 110.3649,
  ),
  HotelEntity(
    city: 'Yogyakarta',
    image: 'assets/hotels/adhistana_hotel.jpg',
    hotelName: 'Adhisthana Hotel Yogyakarta',
    rating: 4.3,
    price: 520000,
    lat: -7.8225,
    long: 110.3695,
  ),
  HotelEntity(
    city: 'Beijing',
    image: 'assets/hotels/rosewood_hotel.jpg',
    hotelName: 'Rosewood Beijing',
    rating: 4.7,
    price: 4800000,
    lat: 39.9156,
    long: 116.4619,
  ),
  HotelEntity(
    city: 'Beijing',
    image: 'assets/hotels/waldorf_hotel.jpg',
    hotelName: 'Waldorf Astoria Beijing',
    rating: 4.8,
    price: 5600000,
    lat: 39.9143,
    long: 116.4095,
  ),
  HotelEntity(
    city: 'Tromsø',
    image: 'assets/hotels/clarion_hotel.jpg',
    hotelName: 'Clarion Hotel The Edge',
    rating: 4.3,
    price: 2600000,
    lat: 69.6487,
    long: 18.9607,
  ),
  HotelEntity(
    city: 'Tromsø',
    image: 'assets/hotels/radisson_blu_hotel.jpg',
    hotelName: 'Radisson Blu Hotel Tromsø',
    rating: 4.4,
    price: 2350000,
    lat: 69.6496,
    long: 18.9560,
  ),
  HotelEntity(
    city: 'Tromsø',
    image: 'assets/hotels/scandic_ishavshotel.jpg',
    hotelName: 'Scandic Ishavshotel',
    rating: 4.8,
    price: 2800000,
    lat: 69.6499,
    long: 18.9585,
  ),
  HotelEntity(
    city: 'Tromsø',
    image: 'assets/hotels/smarthotel.jpg',
    hotelName: 'Smarthotel Tromsø',
    rating: 4.1,
    price: 1450000,
    lat: 69.6513,
    long: 18.9534,
  ),
  HotelEntity(
    city: 'Kyoto',
    image: 'assets/hotels/granvia_hotel.jpg',
    hotelName: 'Hotel Granvia Kyoto',
    rating: 4.5,
    price: 2900000,
    lat: 34.9855,
    long: 135.7585,
  ),
  HotelEntity(
    city: 'Kyoto',
    image: 'assets/hotels/royal_park_hotel.jpg',
    hotelName: 'The Royal Park Hotel Sanjo',
    rating: 4.3,
    price: 1850000,
    lat: 35.0093,
    long: 135.7705,
  ),
  HotelEntity(
    city: 'Santorini',
    image: 'assets/hotels/katikies_santorini.jpg',
    hotelName: 'The Royal Park Hotel Sanjo',
    rating: 4.7,
    price: 4500000,
    lat: 36.4618,
    long: 25.3753,
  ),
  HotelEntity(
    city: 'Santorini',
    image: 'assets/hotels/aressana_hotel.jpg',
    hotelName: 'Aressana Spa Hotel & Suites',
    rating: 4.6,
    price: 3100000,
    lat: 36.4166,
    long: 25.4314,
  ),
  HotelEntity(
    city: 'Serengiti',
    image: 'assets/hotels/four_seasons_safari_lodge.jpg',
    hotelName: 'Four Seasons Safari Lodge Serengeti',
    rating: 4.8,
    price: 12500000,
    lat: -2.3338,
    long: 34.8328,
  ),
  HotelEntity(
    city: 'Serengiti',
    image: 'assets/hotels/melia_serengiti_lodge.jpg',
    hotelName: 'Meliá Serengeti Lodge',
    rating: 4.6,
    price: 9200000,
    lat: 2.3330,
    long: 34.8335,
  ),
  HotelEntity(
    city: 'El Calafate',
    image: 'assets/hotels/xelena_hotel.jpg',
    hotelName: 'Xelena Hotel & Suites',
    rating: 4.4,
    price: 3900000,
    lat: -50.3293,
    long: -72.3006,
  ),
  HotelEntity(
    city: 'El Calafate',
    image: 'assets/hotels/esplendor_hotel.jpg',
    hotelName: 'Esplendor by Wyndham El Calafate',
    rating: 4.3,
    price: 2700000,
    lat: -50.3408,
    long: -72.2637,
  ),
];
